### ISSUE TITLE
Sending "subject" in send_transactional_template update the template not send an email

### ISSUE THREAD

**Issue by mustela** [mailin-api/sendinblue-ruby-gem#2]
This payload sends the email

``` ruby
message = {
          "id" => '1',
          'to' => 'myemail@gmail.com',
          'from' => 'my@anotherdomain.io'
}

result = mailin_instance.send_transactional_template(message)
```

But if I add `subject` to it 

``` ruby
message = {
          "id" => '1',
          'to' => 'myemail@gmail.com',
          'from' => 'my@anotherdomain.io',
          'subject' => 'hello there',
}
```

I'm just getting 

```
=> {"code"=>"success", "message"=>"Updated the Template.", "data"=>[]}
```

So it means I can't send a subject when using `send_transactional_template`? 

Thanks!

**Comment by mustela** [comment]
It seems that using `'to_field' => 'My Name'` also produces an update on the template not it does not send an email.

**Comment by ekta-slit** [comment]
Hello Mustela ,

Thank you for contacting us.

Yes, you can not send a subject when using `send_transactional_template` because it is an invalid input parameter for this API.
Please refer [Apidoc](https://apidocs.sendinblue.com/template/#1) to check all valid input parameters.

Regards,
SendinBlue Team
